# Generated by Django 2.2 on 2019-04-10 23:21

import crawler.utils.base_url_status
import crawler.utils.image_status
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_url', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'deleted')], default=crawler.utils.base_url_status.BaseUrlStatus(0))),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'deleted')], default=crawler.utils.image_status.ImageStatus(0))),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('base_url_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawler.BaseUrl')),
            ],
        ),
    ]
